apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-app-claim
  namespace: project-app-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
