apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-claim
  namespace: log-ping-pong-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
